bigdata/config/routes.rb
Rails.application.routes.draw do
  get 'brands/ford'

  resources :clusters

  resources :combinations

  root 'welcome#home'
  get 'introduction' => 'welcome#introduction'
  get 'by_car' => 'welcome#by_car'
  get 'brands/ford', to: 'brands#ford', via: 'get', as: :ford
  get 'brands/bmw', to: 'brands#bmw', via: 'get', as: :bmw
  get 'brands/chevrolet', to: 'brands#chevrolet', via: 'get', as: :chevrolet
  get 'brands/dodge', to: 'brands#dodge', via: 'get', as: :dodge
  get 'brands/gmc', to: 'brands#gmc', via: 'get', as: :gmc
  get 'brands/honda', to: 'brands#honda', via: 'get', as: :honda
  get 'brands/nissan', to: 'brands#nissan', via: 'get', as: :nissan
  get 'brands/toyota', to: 'brands#toyota', via: 'get', as: :toyota

  post 'redirect' => 'combinations#redirect'

end

bigdata/app/models/cluster.rb
class Cluster < ActiveRecord::Base
  belongs_to :combination
end

bigdata/app/models/combination.rb
class Combination < ActiveRecord::Base
	has_many :clusters
end

bigdata/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bigdata/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def ford
  end

  def gmc
  end

  def nissan
  end

  def toyota
  end

  def dodge
  end

  def bmw
  end

  def chevrolet
  end

  def honda
  end

end

bigdata/app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  before_action :set_cluster, only: [:show, :edit, :update, :destroy]

  # GET /clusters
  # GET /clusters.json
  def index
    @clusters = Cluster.all
  end

  # GET /clusters/1
  # GET /clusters/1.json
  def show
  end

  # GET /clusters/new
  def new
    @cluster = Cluster.new
  end

  # GET /clusters/1/edit
  def edit
  end

  # POST /clusters
  # POST /clusters.json
  def create
    @cluster = Cluster.new(cluster_params)

    respond_to do |format|
      if @cluster.save
        format.html { redirect_to @cluster, notice: 'Cluster was successfully created.' }
        format.json { render :show, status: :created, location: @cluster }
      else
        format.html { render :new }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clusters/1
  # PATCH/PUT /clusters/1.json
  def update
    respond_to do |format|
      if @cluster.update(cluster_params)
        format.html { redirect_to @cluster, notice: 'Cluster was successfully updated.' }
        format.json { render :show, status: :ok, location: @cluster }
      else
        format.html { render :edit }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clusters/1
  # DELETE /clusters/1.json
  def destroy
    @cluster.destroy
    respond_to do |format|
      format.html { redirect_to clusters_url, notice: 'Cluster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cluster
      @cluster = Cluster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cluster_params
      params.require(:cluster).permit(:val1, :val2, :val3, :expn_val, :combination_id)
    end
end

bigdata/app/controllers/combinations_controller.rb
class CombinationsController < ApplicationController
	protect_from_forgery

	before_action :set_combination, only: [:show, :edit, :update, :destroy]

	# GET /combinations
	# GET /combinations.json
	def index
		@combinations = Combination.all

		# params.select! { |k,v| ['age','edu','income','state','occu'].include? k }
		# params.reject! { |k,v| v != 1 }

	end

	def redirect
		array = Array.new(3)
		params[:attr].each do |v| 
			array.push(v)
		end 
		array.reject! { |v| v.nil? || v.empty? }
		array.sort!
		@combination = Combination.where("attr1 = ? AND attr2 = ? AND attr3 = ? AND expn = ?", array[0], array[1], array[2], params[:expn])[0]
		redirect_to @combination
	end

	# GET /combinations/1
	# GET /combinations/1.json
	def show
	end

	# GET /combinations/new
	def new
		@combination = Combination.new
	end

	# GET /combinations/1/edit
	def edit
	end

	# POST /combinations
	# POST /combinations.json
	def create
		@combination = Combination.new(combination_params)

		respond_to do |format|
			if @combination.save
				format.html { redirect_to @combination, notice: 'Combination was successfully created.' }
				format.json { render :show, status: :created, location: @combination }
			else
				format.html { render :new }
				format.json { render json: @combination.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /combinations/1
	# PATCH/PUT /combinations/1.json
	def update
		respond_to do |format|
			if @combination.update(combination_params)
				format.html { redirect_to @combination, notice: 'Combination was successfully updated.' }
				format.json { render :show, status: :ok, location: @combination }
			else
				format.html { render :edit }
				format.json { render json: @combination.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /combinations/1
	# DELETE /combinations/1.json
	def destroy
		@combination.destroy
		respond_to do |format|
			format.html { redirect_to combinations_url, notice: 'Combination was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_combination
			@combination = Combination.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def combination_params
			params.require(:combination).permit(:attr1, :attr2, :attr3, :expn)
		end
end

bigdata/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def introduction
  end

  def by_car
  end

end

bigdata/app/helpers/application_helper.rb
module ApplicationHelper
end

bigdata/app/helpers/brands_helper.rb
module BrandsHelper
end

bigdata/app/helpers/clusters_helper.rb
module ClustersHelper
end

bigdata/app/helpers/combinations_helper.rb
module CombinationsHelper
	def print_val(str)
		if(str.include? '|')
			tmp = "(TOP 3)<br>"
			tokens = str.split('|')
			tokens.each { |token| tmp += "#{token}<br>" }
		else
			tmp = str
		end
		tmp.html_safe
	end

	def print_attr_name(str)
		case str
		when 'edu'
			tmp = 'education'
		when 'ins'
			tmp = 'insurance'
		when 'occu'
			tmp = 'occupation'
		else
			tmp = str
		end

		tmp.upcase
			
	end

end

bigdata/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bigdata/app/views/brands/_group_links.html.erb
<div id="my_sidebar" class="col-sm-3 well">
	<div class="sidebar">
		<ul class="nav nav-pills nav-stacked">
			<li><b>BRAND</b></li>
			<br>
			<li class=<%= 'active' if params[:action] == 'by_car'%>><%= link_to "All Cars", by_car_path%></li>
			<li class=<%= 'active' if params[:action] == 'ford'%>><%= link_to "Ford", ford_path%></li>
			<li class=<%= 'active' if params[:action] == 'bmw'%>><%= link_to "BMW", bmw_path%></li>
			<li class=<%= 'active' if params[:action] == 'chevrolet'%>><%= link_to "Chevrolet", chevrolet_path%></li>
			<li class=<%= 'active' if params[:action] == 'honda'%>><%= link_to "Honda", honda_path%></li>
			<li class=<%= 'active' if params[:action] == 'gmc'%>><%= link_to "GMC", gmc_path%></li>
			<li class=<%= 'active' if params[:action] == 'nissan'%>><%= link_to "Nissan", nissan_path%></li>
			<li class=<%= 'active' if params[:action] == 'dodge'%>><%= link_to "Dodge", dodge_path%></li>
			<li class=<%= 'active' if params[:action] == 'toyota'%>><%= link_to "Toyota", toyota_path%></li>
		</ul>
	</div>
</div>

bigdata/app/views/brands/bmw.html.erb
<div class="inner-wrapper">
	<%= render 'group_links'%>

	<div class="col-sm-9 content">
		<%= link_to '<< Back', root_path %>
		<h1>BMW</h1>
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 1" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 49 years old</li>
					<li>education years = 14 years</li>
					<li>income = 39643 dollars</li>
					<li>car numbers = 36 cars</li>
					<li>car ratio = 37%</li>
				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 33 to 65 years old</li>
					<li>eduation range : from 12 to 16 years</li>
					<li>income range : from 17445 to 61841 dollars</li>

				</ul>
			</div>
		</div>

		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 2" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 49 years old</li>
					<li>education years = 14 years</li>
					<li>income = 127015 dollars</li>
					<li>car numbers = 37 cars</li>
					<li>car ratio = 38%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 37 to 61 years old</li>
					<li>eduation range : from 13 to 15 years</li>
					<li>income range : from 90084 to 163946 dollars</li>

				</ul>
			</div>
		</div>

		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 3" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 42 years old</li>
					<li>education years = 16 years</li>
					<li>income = 341177 dollars</li>
					<li>car numbers = 13 cars</li>
					<li>car ratio = 13%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 32 to 52 years old</li>
					<li>eduation range : from 15 to 17 years</li>
					<li>income range : from 278912 to 403442 dollars</li>

				</ul>
			</div>
		</div>
	</div>
</div>

bigdata/app/views/brands/chevrolet.html.erb
<div class="inner-wrapper">
	<%= render 'group_links'%>

	<div class="col-sm-9 content">
		<%= link_to '<< Back', root_path %>
		<h1>Chevrolet</h1>
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 1" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 49 years old</li>
					<li>education years = 13 years</li>
					<li>income = 76769 dollars</li>
					<li>car numbers = 465 cars</li>
					<li>car ratio = 37%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 36 to 62 years old</li>
					<li>eduation range : from 11 to 15 years</li>
					<li>income range : from 57565 to 95973 dollars</li>

				</ul>
			</div>
		</div>
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 2" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 66 years old</li>
					<li>education years = 12 years</li>
					<li>income = 23521 dollars</li>
					<li>car numbers = 363 cars</li>
					<li>car ratio = 29%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 55 to 77 years old</li>
					<li>eduation range : from 10 to 14 years</li>
					<li>income range : from 10233 to 36809 dollars</li>

				</ul>
			</div>
		</div>

		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 3" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 34 years old</li>
					<li>education years = 13 years</li>
					<li>income = 29300 dollars</li>
					<li>car numbers = 320 cars</li>
					<li>car ratio = 25%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 25 to 43 years old</li>
					<li>eduation range : from 11 to 15 years</li>
					<li>income range : from 14801 to 43799 dollars</li>

				</ul>
			</div>
		</div>
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 4" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 50 years old</li>
					<li>education years = 14 years</li>
					<li>income = 203768 dollars</li>
					<li>car numbers = 96 cars</li>
					<li>car ratio = 7%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 39 to 61 years old</li>
					<li>eduation range : from 12 to 16 years</li>
					<li>income range : from 54480 to 353056 dollars</li>

				</ul>
			</div>
		</div>
	</div>
</div>

bigdata/app/views/brands/dodge.html.erb
<div class="inner-wrapper">
	<%= render 'group_links'%>

	<div class="col-sm-9 content">
		<%= link_to '<< Back', root_path %>
		<h1>Dodge</h1>
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 1" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 60 years old</li>
					<li>education years = 13 years</li>
					<li>income = 15677 dollars</li>
					<li>car numbers = 113 cars</li>
					<li>car ratio = 23%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 42 to 78 years old</li>
					<li>eduation range : from 12 to 14 years</li>
					<li>income range : from 5582 to 25772 dollars</li>

				</ul>
			</div>
		</div>
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 2" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 44 years old</li>
					<li>education years = 13 years</li>
					<li>income = 49394 dollars</li>
					<li>car numbers = 241 cars</li>
					<li>car ratio = 50%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 30 to 58 years old</li>
					<li>eduation range : from 12 to 14 years</li>
					<li>income range : from 32086 to 66702 dollars</li>

				</ul>
			</div>
		</div>

		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER 3" %></h3>
			</div>
			<div class="panel-body">
				<ul>
					<li>age = 46 years old</li>
					<li>education years = 14 years</li>
					<li>income = 133194 dollars</li>
					<li>car numbers = 121 cars</li>
					<li>car ratio = 25%</li>

				</ul>
				<br>
				<p>number range:</p>
				<ul>
					<li>age range : from 34 to 58 years old</li>
					<li>eduation range : from 13 to 15 years</li>
					<li>income range : from 44268 to 222120 dollars</li>

				</ul>
			</div>
		</div>
	</div>
</div>

bigdata/app/views/clusters/edit.html.erb
<h1>Editing Cluster</h1>

<%= render 'form' %>

<%= link_to 'Show', @cluster %> |
<%= link_to 'Back', clusters_path %>

bigdata/app/views/clusters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clusters</h1>

<table>
  <thead>
    <tr>
      <th>Val1</th>
      <th>Val2</th>
      <th>Val3</th>
      <th>Expn val</th>
      <th>Combination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clusters.each do |cluster| %>
      <tr>
        <td><%= cluster.val1 %></td>
        <td><%= cluster.val2 %></td>
        <td><%= cluster.val3 %></td>
        <td><%= cluster.expn_val %></td>
        <td><%= cluster.combination %></td>
        <td><%= link_to 'Show', cluster %></td>
        <td><%= link_to 'Edit', edit_cluster_path(cluster) %></td>
        <td><%= link_to 'Destroy', cluster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cluster', new_cluster_path %>

bigdata/app/views/clusters/new.html.erb
<h1>New Cluster</h1>

<%= render 'form' %>

<%= link_to 'Back', clusters_path %>

bigdata/app/views/clusters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Val1:</strong>
  <%= @cluster.val1 %>
</p>

<p>
  <strong>Val2:</strong>
  <%= @cluster.val2 %>
</p>

<p>
  <strong>Val3:</strong>
  <%= @cluster.val3 %>
</p>

<p>
  <strong>Expn val:</strong>
  <%= @cluster.expn_val %>
</p>

<p>
  <strong>Combination:</strong>
  <%= @cluster.combination %>
</p>

<%= link_to 'Edit', edit_cluster_path(@cluster) %> |
<%= link_to 'Back', clusters_path %>

bigdata/app/views/combinations/edit.html.erb
<h1>Editing Combination</h1>

<%= render 'form' %>

<%= link_to 'Show', @combination %> |
<%= link_to 'Back', combinations_path %>

bigdata/app/views/combinations/index.html.erb
<div class="inner-wrapper">
<%= link_to '<< Back', root_path %>

<h1>Inspect Clusters</h1>
<div class="alert alert-warning" role="alert">
	<p><b>WARNING: </b>Exactly 3 dimentions should be selected in Demographic Info</p>
</div>
<form class="form-horizontal" action="/redirect" method="post">
	<div class="form-group">
		<label for="age-box" class="col-sm-2 control-label">Demographic Info</label>
		<div id="input" class="col-sm-2" data-container="body" data-toggle="popover" data-placement="right" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
			<div class="checkbox">
				<label>
					<input type="checkbox" class="form-control" id="age-box" name="attr[]" onClick="return KeepCount()" value="age" checked="checked">Age<br>
				</label>
			</div>

			<div class="checkbox">
				<label>
					<input type="checkbox" name="attr[]" onClick="return KeepCount()" value="edu" checked="checked">Education<br>
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="attr[]" onClick="return KeepCount()" value="income" checked="checked">Income<br>
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="attr[]" onClick="return KeepCount()" value="occu">Occupation<br>
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="attr[]" onClick="return KeepCount()" value="state">State<br>
				</label>
			</div>
		</div>
		<label for="car-box" class="col-sm-2 control-label">Expenditure</label>
		<div class="col-sm-2">
			<div class="radio">
				<label>
					<input type="radio" name="expn" value="car" checked="checked">Car<br>
				</label>
			</div>
			<div class="radio">
				<label>
					<input type="radio" name="expn" value="ins">Insurance<br>
				</label>
			</div>
		</div>
		<button type="submit" class="btn btn-primary col-sm-2">Submit</button>
	</div>
	
	
</form>


<!-- <table>
	<thead>
		<tr>
			<th>Attr1</th>
			<th>Attr2</th>
			<th>Attr3</th>
			<th>Expn</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @combinations.each do |combination| %>
			<tr>
				<td><%= combination.attr1 %></td>
				<td><%= combination.attr2 %></td>
				<td><%= combination.attr3 %></td>
				<td><%= combination.expn %></td>
				<td><%= link_to 'Show', combination %></td>
				<td><%= link_to 'Edit', edit_combination_path(combination) %></td>
				<td><%= link_to 'Destroy', combination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Combination', new_combination_path %>   -->
<script type="text/javascript">

	$('input[type=checkbox]').on('change', function (e) {
	    if ($('input[type=checkbox]:checked').length > 3) {
	        $(this).prop('checked', false);
	        alert("allowed only 3");
	    }
	});

</script>
</div>

bigdata/app/views/combinations/new.html.erb
<h1>New Combination</h1>

<%= render 'form' %>

<%= link_to 'Back', combinations_path %>

bigdata/app/views/combinations/show.html.erb
<div class="inner-wrapper">
	<%= link_to '<< Back', combinations_path %>
	<div class="title">
		<h2>
			<%= print_attr_name(@combination.attr1) %>,
			<%= print_attr_name(@combination.attr2) %>,
			<%= print_attr_name(@combination.attr3) %> +
			<%= print_attr_name(@combination.expn) %>
		</h2>
	</div>
	<br>
	<% if @combination.expn == 'ins' %>
		<P><strong>Insurance code:</strong></p>
		<ul>
			<li>100 Life insurance, or other policies which provide benefits in case of death or disability</li>
			<li>110 Long Term Care insurance</li>
			<li>200 Automobile or other vehicle insurance</li>
			<li>300 Homeowner's insurance</li>
			<li>400 Renter's insurance</li>
			<li>500 Other types of non-health insurance </li>
			<li>900 Combined insurance</li>
		</ul>
	<% elsif @combination.expn == 'car' %>
		<P><strong>Car type code:</strong></p>
		<ul>
			<li>100 Automobile</li>
			<li>110 Truck, including vans</li>
		</ul>
	<% end %>
	<% i = 0 %>
	<% @combination.clusters.each do |cluster| %>
		<% i += 1 %>
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER #{i}" %></h3>
			</div>
			<div class="panel-body">
				<p>
				  <strong><%= print_attr_name(@combination.attr1) %></strong>
				  <%= print_val(cluster.val1) %>
				</p>

				<p>
				  <strong><%= print_attr_name(@combination.attr2) %></strong>
				  <%= print_val(cluster.val2) %>
				</p>

				<p>
				  <strong><%= print_attr_name(@combination.attr3) %></strong>
				  <%= print_val(cluster.val3) %>
				</p>

				<p>
				  <strong><%= @combination.expn.upcase %></strong>
				  <%= print_val(cluster.expn_val) %>
				</p>
			</div>
		</div>

	<% end %>

</div>

bigdata/app/views/layouts/_footer.html.erb
<footer>

	<center>Columbia University | Big Data Analytics</center>

</footer>

bigdata/app/views/layouts/_header.html.erb
<header id="nav" class="navbar-fixed-top">
	<div class="navbar-header">
		
		<a id="logo" href=<%= root_url%>>SAPPHIRINE</a>
		
	</div>
	<ul class="nav navbar-nav pull-right">
		
		<li><%= link_to "Our Project", introduction_path%></li>
		<li><%= link_to "Inspect Clusters", combinations_path%></li>
		<li><%= link_to "Group People by Car", by_car_path%></li>

	</ul>

</header>

bigdata/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sapphirine</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header'%>
	
	<div class="container-fluid" id="wrapper">

		<div class="row-fluid">
			<%= yield%>
		</div>
	</div>

	<%= render 'layouts/footer'%>
</body>
</html>

bigdata/app/views/welcome/_group_links.html.erb
<div id="my_sidebar" class="col-sm-3 well">
	<div class="sidebar">
		<ul class="nav nav-pills nav-stacked">
			<li><b>BRAND</b></li>
			<br>
			<li class=<%= 'active' if params[:action] == 'by_car'%>><%= link_to "All Cars", by_car_path%></li>
			<li class=<%= 'active' if params[:action] == 'ford'%>><%= link_to "Ford", ford_path%></li>
			<li class=<%= 'active' if params[:action] == 'bmw'%>><%= link_to "BMW", bmw_path%></li>
			<li class=<%= 'active' if params[:action] == 'chevrolet'%>><%= link_to "Chevrolet", chevrolet_path%></li>
			<li class=<%= 'active' if params[:action] == 'honda'%>><%= link_to "Honda", honda_path%></li>
			<li class=<%= 'active' if params[:action] == 'gmc'%>><%= link_to "GMC", gmc_path%></li>
			<li class=<%= 'active' if params[:action] == 'nissan'%>><%= link_to "Nissan", nissan_path%></li>
			<li class=<%= 'active' if params[:action] == 'dodge'%>><%= link_to "Dodge", dodge_path%></li>
			<li class=<%= 'active' if params[:action] == 'toyota'%>><%= link_to "Toyota", toyota_path%></li>
		</ul>
	</div>
</div>

bigdata/app/views/welcome/home.html.erb
<div class="span10 offset1">
	<div id="my-carousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
		<li data-target="#my-carousel" data-slide-to="0" class="active"></li>
		<li data-target="#my-carousel" data-slide-to="1"></li>
		<li data-target="#my-carousel" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<%= image_tag("bigdata.png", :alt => "bigdata") %>
			</div>
			<div class="item">
				<%= image_tag("people.jpg", :alt => "people") %>
			</div>
			<div class="item">
				<%= image_tag("cars.png", :alt => "cars") %>
			</div>
		</div>
	</div>
	<div style="margin-left:27px">
		<h2>Market Strategy Suggestions for B2C Websites</h2>
		<p>-- Siyuan Zhang, Wenxin Wang, Xuebo Wang, Zixuan Gong</p>
	</div>
	<div class="row-fluid need-padding">
		<div class="col-md-4">
			<h3>Our Project</h3>
			<p>Our project is about Market Strategy Suggestions for B2C Websites. Here we introduce the project, the dataset, and the algorithms we use</p>
			<p>
				<a class="btn btn-default" href=<%= introduction_path %> role="button">View details</a>
			</p>
		</div>
		<div class="col-md-4">
			<h3>Inspect Clusters</h3>
			<p>In our java program, we do clustering with all the dimensions we are interested in. Here is some pre-processed data as an example</p>
			<p>
				<a class="btn btn-default" href=<%= combinations_path %> role="button">View details</a>
			</p>
		</div>
		<div class="col-md-4">
			<h3>Cluster By Car</h3>
			<p>We also did clustering on the people that have a specific car, using their age, education level, and income as dimensions</p>

			<p>
				<a class="btn btn-default" href=<%= by_car_path %> role="button">View details</a>
			</p>
		</div>
	</div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
		    $('.carousel').carousel({
				interval: 3000
			});
		});
	</script>

</div>